id: A14EE1A6E
title: 'An Envoy for Swiftly Invoking the Blessings of Definitive Meaning: Calling
  the Great Omniscient Jonangpa from Afar'
type: translation
pechas:
- IA82AFF06
- I4E5C09CC
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:09:02.608206
  last_modified_at: 2023-01-04 12:09:02.608210
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  IA82AFF06/40F0: 4DCE
  I4E5C09CC/04EA: 4DCE
